//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/InputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystem"",
    ""maps"": [
        {
            ""name"": ""CardGame"",
            ""id"": ""70454ef2-cf61-40d0-a835-a2a596827443"",
            ""actions"": [
                {
                    ""name"": ""Touch"",
                    ""type"": ""Button"",
                    ""id"": ""5155df44-5a1c-47d9-ba0e-bb13749562c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""KeyboardAny"",
                    ""type"": ""Button"",
                    ""id"": ""31d9b80d-eaed-4c3b-a5bf-532dbc83357f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Swipe"",
                    ""type"": ""Value"",
                    ""id"": ""4edd0af7-4b79-494f-84c9-52b1aef0d3ae"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Tap"",
                    ""type"": ""Button"",
                    ""id"": ""e29e9ea6-51d7-4566-be1b-6f4f321098c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Area"",
                    ""type"": ""Value"",
                    ""id"": ""795d91ac-528a-41a8-be01-9fb858388227"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""haspressedscreen"",
                    ""type"": ""Button"",
                    ""id"": ""b4b4a79d-840c-455e-84ab-8c31e3f544db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePress"",
                    ""type"": ""Button"",
                    ""id"": ""6fb4399e-8599-4d3a-8173-ef2b44c5ab66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""f5f4060d-d4e0-4bc2-90a3-3a20d2e2ece8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6a579392-24bf-4cab-9fa9-719524cc96a2"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cad7ffb5-2b97-4e7f-9b8d-014235f4add2"",
                    ""path"": ""<Touchscreen>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a843791-36ef-46d4-aea2-300db36b4008"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d1ee6d5-e883-4f10-b4ad-8a49a71f8fd9"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardAny"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c406f665-8d23-4c9d-8945-b0a12e2ecbc3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swipe"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""af5f7a9e-eaed-4d47-a88d-7993cf2355ed"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2286d208-a98d-4e72-be74-d0965199d8dd"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a516a621-6e81-4067-b345-bf9585e61296"",
                    ""path"": ""<Keyboard>/#(D)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""50618281-85bd-45a4-a00f-d83407ff276f"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""332352d2-83fd-418e-a4b6-014fc40407cc"",
                    ""path"": ""<Touchscreen>/position/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Area"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""474aec21-96d8-48bc-b6c5-9ddd4aade7bd"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""haspressedscreen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20a2bca1-c48d-4230-9099-1d35ddbd75d3"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cce33c97-07fd-4505-9d47-a39b32eee6f7"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CardGame
        m_CardGame = asset.FindActionMap("CardGame", throwIfNotFound: true);
        m_CardGame_Touch = m_CardGame.FindAction("Touch", throwIfNotFound: true);
        m_CardGame_KeyboardAny = m_CardGame.FindAction("KeyboardAny", throwIfNotFound: true);
        m_CardGame_Swipe = m_CardGame.FindAction("Swipe", throwIfNotFound: true);
        m_CardGame_Tap = m_CardGame.FindAction("Tap", throwIfNotFound: true);
        m_CardGame_Area = m_CardGame.FindAction("Area", throwIfNotFound: true);
        m_CardGame_haspressedscreen = m_CardGame.FindAction("haspressedscreen", throwIfNotFound: true);
        m_CardGame_MousePress = m_CardGame.FindAction("MousePress", throwIfNotFound: true);
        m_CardGame_MousePosition = m_CardGame.FindAction("MousePosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CardGame
    private readonly InputActionMap m_CardGame;
    private List<ICardGameActions> m_CardGameActionsCallbackInterfaces = new List<ICardGameActions>();
    private readonly InputAction m_CardGame_Touch;
    private readonly InputAction m_CardGame_KeyboardAny;
    private readonly InputAction m_CardGame_Swipe;
    private readonly InputAction m_CardGame_Tap;
    private readonly InputAction m_CardGame_Area;
    private readonly InputAction m_CardGame_haspressedscreen;
    private readonly InputAction m_CardGame_MousePress;
    private readonly InputAction m_CardGame_MousePosition;
    public struct CardGameActions
    {
        private @InputSystem m_Wrapper;
        public CardGameActions(@InputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Touch => m_Wrapper.m_CardGame_Touch;
        public InputAction @KeyboardAny => m_Wrapper.m_CardGame_KeyboardAny;
        public InputAction @Swipe => m_Wrapper.m_CardGame_Swipe;
        public InputAction @Tap => m_Wrapper.m_CardGame_Tap;
        public InputAction @Area => m_Wrapper.m_CardGame_Area;
        public InputAction @haspressedscreen => m_Wrapper.m_CardGame_haspressedscreen;
        public InputAction @MousePress => m_Wrapper.m_CardGame_MousePress;
        public InputAction @MousePosition => m_Wrapper.m_CardGame_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_CardGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CardGameActions set) { return set.Get(); }
        public void AddCallbacks(ICardGameActions instance)
        {
            if (instance == null || m_Wrapper.m_CardGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CardGameActionsCallbackInterfaces.Add(instance);
            @Touch.started += instance.OnTouch;
            @Touch.performed += instance.OnTouch;
            @Touch.canceled += instance.OnTouch;
            @KeyboardAny.started += instance.OnKeyboardAny;
            @KeyboardAny.performed += instance.OnKeyboardAny;
            @KeyboardAny.canceled += instance.OnKeyboardAny;
            @Swipe.started += instance.OnSwipe;
            @Swipe.performed += instance.OnSwipe;
            @Swipe.canceled += instance.OnSwipe;
            @Tap.started += instance.OnTap;
            @Tap.performed += instance.OnTap;
            @Tap.canceled += instance.OnTap;
            @Area.started += instance.OnArea;
            @Area.performed += instance.OnArea;
            @Area.canceled += instance.OnArea;
            @haspressedscreen.started += instance.OnHaspressedscreen;
            @haspressedscreen.performed += instance.OnHaspressedscreen;
            @haspressedscreen.canceled += instance.OnHaspressedscreen;
            @MousePress.started += instance.OnMousePress;
            @MousePress.performed += instance.OnMousePress;
            @MousePress.canceled += instance.OnMousePress;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
        }

        private void UnregisterCallbacks(ICardGameActions instance)
        {
            @Touch.started -= instance.OnTouch;
            @Touch.performed -= instance.OnTouch;
            @Touch.canceled -= instance.OnTouch;
            @KeyboardAny.started -= instance.OnKeyboardAny;
            @KeyboardAny.performed -= instance.OnKeyboardAny;
            @KeyboardAny.canceled -= instance.OnKeyboardAny;
            @Swipe.started -= instance.OnSwipe;
            @Swipe.performed -= instance.OnSwipe;
            @Swipe.canceled -= instance.OnSwipe;
            @Tap.started -= instance.OnTap;
            @Tap.performed -= instance.OnTap;
            @Tap.canceled -= instance.OnTap;
            @Area.started -= instance.OnArea;
            @Area.performed -= instance.OnArea;
            @Area.canceled -= instance.OnArea;
            @haspressedscreen.started -= instance.OnHaspressedscreen;
            @haspressedscreen.performed -= instance.OnHaspressedscreen;
            @haspressedscreen.canceled -= instance.OnHaspressedscreen;
            @MousePress.started -= instance.OnMousePress;
            @MousePress.performed -= instance.OnMousePress;
            @MousePress.canceled -= instance.OnMousePress;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
        }

        public void RemoveCallbacks(ICardGameActions instance)
        {
            if (m_Wrapper.m_CardGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICardGameActions instance)
        {
            foreach (var item in m_Wrapper.m_CardGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CardGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CardGameActions @CardGame => new CardGameActions(this);
    public interface ICardGameActions
    {
        void OnTouch(InputAction.CallbackContext context);
        void OnKeyboardAny(InputAction.CallbackContext context);
        void OnSwipe(InputAction.CallbackContext context);
        void OnTap(InputAction.CallbackContext context);
        void OnArea(InputAction.CallbackContext context);
        void OnHaspressedscreen(InputAction.CallbackContext context);
        void OnMousePress(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
}
